apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: hc-manager
  name: hc-manager-{{.SHARD}}
  namespace: projectsveltos
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: hc-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: hc-manager
    spec:
      containers:
      - args:
        - --diagnostics-address=:8443
        - --shard-key={{.SHARD}}
        - --capi-onboard-annotation=
        - --v=5
        - --version=main
        - --agent-in-mgmt-cluster=false
        command:
        - /manager
        image: docker.io/projectsveltos/healthcheck-manager@sha256:2e2ebcee06134a6a9e45a9b29c7ff76d7d3d0bcf9d9f49fe0e17c803c423af71
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: hc-manager
      terminationGracePeriodSeconds: 10
